[flags]
store = "mysql"
verbose = true


[web]
username = "admin"
password = "123"

[apps]
[apps.myapp]
description = "myapp"
root = "/data/www/myapp"
prefix = ""
tmpl = ".env.tmpl"
dist = ".env"
cmd = "nginx -s reload"

[apps.myapp2]
description = "myapp2"
root = "/data/www/myapp2"
cmd = ""

[backends]
[backends.redis]
host = "127.0.0.1"
port = 6379
db = 0
password = ""

[backends.postgres]
dsn="postgres://root:dev@localhost:5432/econfig?sslmode=disable"

[backends.mysql]
dsn="root:dev@tcp(localhost:3306)/econfig"

